-- DROP TABLE IF EXISTS endpoint_hits CASCADE;

CREATE TABLE IF NOT EXISTS endpoint_hits (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    app         VARCHAR(100)                              NOT NULL,
    uri         VARCHAR(1000)                              NOT NULL,
    ip          VARCHAR(20)                               NOT NULL,
    timestamp   TIMESTAMP                                 NOT NULL,
    CONSTRAINT pk_endpoint_hits PRIMARY KEY (id)
);